# Generated by Django 4.0.6 on 2022-07-19 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='RecipeDateAdded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='RecipeDateUpdated',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 13, 31, 26, 453889, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='UserDateAdded',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 13, 31, 26, 493006, tzinfo=utc)),
        ),
    ]
