# Generated by Django 4.0.6 on 2022-07-19 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe_recipephoto_name_user_userphoto_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberId', models.AutoField(primary_key=True, serialize=False)),
                ('MemberFName', models.CharField(max_length=30)),
                ('MemberLName', models.CharField(max_length=30)),
                ('MemberDateAdded', models.DateField(default=datetime.datetime(2022, 7, 19, 16, 18, 25, 799182, tzinfo=utc))),
                ('MemberPhoto_name', models.CharField(max_length=100)),
                ('MemberPhoto_file', models.ImageField(upload_to='images')),
                ('MemberPhoto_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='RecipeDateUpdated',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 16, 18, 25, 761436, tzinfo=utc)),
        ),
    ]
