# Generated by Django 4.0.6 on 2022-07-19 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_member_delete_user_alter_recipe_recipedateupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='MemberRecipes',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='MemberDateAdded',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 16, 33, 9, 467339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='RecipeDateUpdated',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 16, 33, 9, 408312, tzinfo=utc)),
        ),
    ]
