# Generated by Django 4.0.6 on 2022-07-19 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_member_memberdateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MemberDateAdded',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 18, 19, 45, 976158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='RecipeDateAdded',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 18, 19, 45, 938903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='RecipeDateUpdated',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 18, 19, 45, 939248, tzinfo=utc)),
        ),
    ]
